import 'dotenv/config';
import crypto from 'node:crypto';
import { chromium } from '@playwright/test';
const BASE = 'http://localhost:3000';
const { prisma } = await import('./lib/db');
const account = await prisma.megaAccount.findUnique({ where: { id: 1 }, select: { userId: true } });
const token = crypto.randomBytes(32).toString('hex');
await prisma.session.create({ data: { userId: account!.userId, token, expiresAt: new Date(Date.now() + 10*60_000) } });
console.log('token minted');
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--mute-audio'] });
const context = await browser.newContext({ viewport: { width: 1280, height: 800 } });
await context.addCookies([{ name: 'session_token', value: token, url: BASE }]);
const page = await context.newPage();
page.on('console', (m) => { if (m.type() === 'error') console.log('CONSOLE-ERR:', m.text().slice(0,300)); });
page.on('response', (r) => { if (r.status() >= 400) console.log('HTTP', r.status(), r.url().replace(BASE,'')); });
await page.goto(`${BASE}/video/pov-vile-strap-on-sissification-cei`, { waitUntil: 'domcontentloaded', timeout: 60000 });
await page.waitForTimeout(8000);
console.log('url:', page.url());
console.log('title:', await page.title());
const body = await page.evaluate(() => document.body.innerText.slice(0, 800));
console.log('BODY:', JSON.stringify(body));
console.log('video count:', await page.locator('video').count());
await page.screenshot({ path: '/tmp/opencode/debug-page.png' });
await browser.close();
await prisma.session.deleteMany({ where: { token } });
await prisma.$disconnect();
